volumes:
  calculator-postgres:

services:
  calculator-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - calculator-postgres:/var/lib/postgresql/data